[project]
name = "repl-nix-aiagencytoolkit"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-login>=0.6.3",
    "flask-wtf>=1.2.2",
    "trafilatura>=2.0.0",
]
